# Generated by Django 6.1.2 on 2026-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='expedientes/'),
        ),
    ]
